### ISSUE TITLE
General Setup Script - add Homebrew to PATH

### ISSUE THREAD

**Issue by ahohnsen** [neuefische/web-setup#2]
I updated to **macOs Ventura** and ran the **General Setup Script** afterwards.

I had the following problem:

- Homebrew was successfully installed but I got the **warning**:

> /opt/homebrew/bin is not in your PATH.

- Afterwards I get asked to run three commands to add Homebrew to my PATH.
- But before I can do so the script continues with installing the Command Line Tools and other tools/apps. ➡️ I get the following error:

> command not found: brew

I fixed this by:
- running the three commands to add Homebrew to my PATH
- running the **General Setup Script** again

Maybe there is a way to pause the script until the user has copied the three commands to add Homebrew to the PATH before it continues with the installation of the other tools/apps.
As far as I remember, we always had to run these commands manually, so this should not be related to the  **macOs Ventura** update.

![Screenshot 2023-01-06 at 16 51 59](https://user-images.githubusercontent.com/94636438/211048011-12ed5f21-104d-4c20-a7fa-308b0ebab566.png)

**Comment by mpagels** [comment]
Very good catch. I recommend putting these three lines in the `setup` script.

# Acceptance criteria
- extract username in variable
- run the two lines with this variable
- run third line

I will do that.

**Comment by PReichetanz** [comment]
Great, thank you @mpagels!
